name: CMS - Continuous Delivery
concurrency: cd
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "infrastructure/**"
      - "apps/cms/**"

defaults:
  run:
    working-directory: apps/cms

env:
  PUBLISH_PATH: '/${{ github.workspace }}/cms/publish'
  DOWNLOAD_PATH: '/${{ github.workspace }}/cms/download'
  CMS_ARTIFACT_NAME: 'cms_artifact'

jobs:
  build_cms:
    name: Build CMS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build CMS
        run: dotnet build --no-restore -c Release
      - name: Publish CMS package
        run: dotnet publish -c Release --property:PublishDir='${{ env.PUBLISH_PATH }}' 
      - name: Upload CMS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CMS_ARTIFACT_NAME }}
          path: ${{ env.PUBLISH_PATH }}
 
  deploy_infra:
    name: Deploy CMS infrastructure
    runs-on: ubuntu-latest
    outputs:
      appServiceName: ${{ steps.deploy.outputs.appServiceName }}
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy infrastructure
        id: deploy
        uses: azure/arm-deploy@v2
        with:
            scope: 'subscription'
            region: 'germanywestcentral'
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            template: ./infrastructure/cms.bicep
            parameters: 'environment=production'

  deploy_application:
    name: Deploy CMS application
    runs-on: ubuntu-latest
    needs: [build_cms, deploy_infra]
    steps:
      - name: Download CMS artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.CMS_ARTIFACT_NAME }}
          path: ${{ env.DOWNLOAD_PATH }}
      - uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ needs.deploy_infra.outputs.appServiceName }}
          package: ${{ env.DOWNLOAD_PATH }}

